historic_path: "src/vsti_vapi_modelo_predictivo_apis_dev/static/excel/mes_marzo.xlsx"
output_dir: "src/vsti_vapi_modelo_predictivo_apis_dev/static/feature_pipeline_output"
features:
  freq: "5min"
  lag_list: [1,2,3,6,12]
  rolling_windows: [12,36,288]
  ema_spans: [3,12,48]
  prev_day_shift: 288
